# Generated by Django 5.2 on 2025-05-05 02:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("article_system", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="causes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="article",
            name="symptoms",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="article",
            name="topic_type",
            field=models.CharField(
                choices=[
                    ("Disease", "Disease"),
                    ("Tools", "Tools"),
                    ("Medicine", "Medicine"),
                    ("Behaviour", "Behaviour"),
                ],
                max_length=20,
            ),
        ),
    ]
