# Generated by Django 5.2 on 2025-07-10 01:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("article_system", "0003_article_caption_alter_article_creator"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="article",
            name="causes",
        ),
        migrations.RemoveField(
            model_name="article",
            name="topic_type",
        ),
    ]
