# Generated by Django 5.2 on 2025-07-11 03:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("article_system", "0005_comment_to_article_comment_to_comment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="article",
            name="symptoms",
        ),
    ]
