# Generated by Django 5.2 on 2025-07-12 02:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("article_system", "0006_remove_article_symptoms"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="num_like",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
