# Generated by Django 5.2 on 2025-07-12 09:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("article_system", "0007_article_num_like"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="article",
            name="num_like",
        ),
    ]
