# Generated by Django 5.2 on 2025-05-11 03:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("epidemic_stoper_system", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="epidemic",
            name="topic",
            field=models.TextField(blank=True, null=True),
        ),
    ]
