# Generated by Django 5.2 on 2025-06-20 11:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("epidemic_stoper_system", "0002_epidemic_topic"),
    ]

    operations = [
        migrations.RenameField(
            model_name='Epidemic',
            old_name='creator',
            new_name='author',
        ),
    ]
