# Generated by Django 5.2 on 2025-06-22 10:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("epidemic_stoper_system", "0003_auto_20250620_1746"),
    ]

    operations = [
        migrations.AddField(
            model_name="epidemic",
            name="food_avoid",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="epidemic",
            name="food_take",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="epidemic",
            name="lifestyle_avoid",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="epidemic",
            name="lifestyle_take",
            field=models.TextField(blank=True, null=True),
        ),
    ]
