# Generated by Django 5.2 on 2025-06-23 02:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "epidemic_stoper_system",
            "0004_epidemic_food_avoid_epidemic_food_take_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="epidemic",
            name="managing_tips",
        ),
        migrations.RemoveField(
            model_name="epidemic",
            name="prevention_tips",
        ),
    ]
