# Generated by Django 5.2 on 2025-06-23 02:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("epidemic_stoper_system", "0005_remove_epidemic_managing_tips_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="epidemic",
            name="managing_tips",
            field=models.TextField(blank=True, null=True),
        ),
    ]
