# Generated by Django 5.2 on 2025-07-21 08:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("epidemic_stoper_system", "0006_epidemic_managing_tips"),
    ]

    operations = [
        migrations.AlterField(
            model_name="epidemic",
            name="name",
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
