# Generated by Django 5.2 on 2025-07-21 08:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ai_diagnosis_app", "0002_remove_diseases_for_ai_symptoms"),
    ]

    operations = [
        migrations.AlterField(
            model_name="diseases_for_ai",
            name="disease_name",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
