# Generated by Django 5.2 on 2025-07-30 07:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ai_diagnosis_app", "0008_alter_user_disease_report_created_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user_disease_report",
            name="created_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
