# Generated by Django 5.2 on 2025-07-11 01:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account_system", "0002_alter_user_account_first_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user_account",
            name="username",
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
